<?php
declare(strict_types=1);

namespace PunktDe\SiteSpecifics\Tests\Functional\NodeTypePostProcessor;

/*
 *  (c) 2021 punkt.de GmbH - Karlsruhe, Germany - http://punkt.de
 *  All rights reserved.
 */

use Neos\ContentRepository\Domain\Service\NodeTypeManager;
use Neos\Flow\Tests\FunctionalTestCase;
use Neos\Utility\Arrays;

class SiteSpecificNodeTypePostProcessorTest extends FunctionalTestCase
{

    protected ?NodeTypeManager $nodeTypeManager;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->nodeTypeManager = $this->objectManager->get(NodeTypeManager::class);
    }

    public function configurationTestDataProvider(): array
    {
        return [
            'simple value override' => [
                'path' => 'ui.group',
                'config' => 'not-shown'
            ]
        ];
    }


    /**
     * @dataProvider configurationTestDataProvider
     * @test
     * @param string $path
     * @param $config
     * @throws \Neos\ContentRepository\Exception\NodeTypeNotFoundException
     */
    public function siteSpecificOverrides(string $path, $config): void
    {
        $nodeTypeConfiguration = $this->nodeTypeManager->getNodeType('PunktDe.SiteSpecifics:Content.Headline')->getFullConfiguration();
        \Neos\Flow\var_dump($nodeTypeConfiguration, __METHOD__ . ':' . __LINE__);
        self::assertEquals($config, Arrays::getValueByPath($nodeTypeConfiguration, $path));
    }
}
